'use strict';
const SERVICE_STATES=new Set(['lead','orcamento','agendado','producao','entregue','pago','perdido']);
const AGENDA_LIFECYCLE=new Set(['planejado','feito']);
const ATTR_KEYS=['tracking_ref','gclid','gbraid','wbraid','utm_source','utm_medium','utm_campaign','campaign_id','ad_group_id','ad_id'];
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function result(value,certainty='known',reason=null){return{value,certainty,reason}}
function serviceStage(item){const s=norm(item?.status??item?.stage);if(SERVICE_STATES.has(s))return result(s);return result('etapa_indeterminada','insufficient',s?'servico_status_desconhecido':'servico_sem_status')}
function agendaLifecycle(item){const s=norm(item?.status);if(AGENDA_LIFECYCLE.has(s))return result(s);return result('estado_indeterminado','insufficient',s?'agenda_status_desconhecido':'agenda_sem_status')}
function agendaCertainty(item){const c=norm(item?.certainty??item?.confirmacao);if(['confirmado','provisorio','sugestao'].includes(c))return result(c);return result('nao_registrada','insufficient','agenda_sem_certeza_explicita')}
function isReceivedRevenue(entry){const type=norm(entry?.tipo??entry?.direction),scope=norm(entry?.escopo??entry?.scope),status=norm(entry?.status),amount=Number(entry?.valor??entry?.amount);if(type!=='entrada'||scope!=='empresa')return result(false);if(!Number.isFinite(amount)||amount<=0)return result(false,'insufficient','valor_financeiro_invalido');if(status==='pago')return result(true);if(status==='a_receber')return result(false);if(status==='a_pagar')return result(false,'insufficient','entrada_com_status_a_pagar');if(!status)return result(false,'insufficient','entrada_sem_status');return result(false,'insufficient','entrada_status_desconhecido')}
function marketingAttribution(record){const evidence=ATTR_KEYS.filter(k=>String(record?.[k]??'').trim());if(!evidence.length)return result(null,'insufficient','sem_evidencia_de_atribuicao');return result({evidence})}
function requiredHumanDecision(item){if(item?.ambiguity===true)return result(true,'known','ambiguidade_explicita');if(item?.external_write===true&&item?.approved!==true)return result(true,'known','escrita_externa_sem_aprovacao');if(item?.missing_required_fact===true)return result(true,'known','fato_obrigatorio_ausente');return result(false)}
function runChecks(input={}){const divergences=[];for(const s of input.services??[]){const r=serviceStage(s);if(r.certainty==='insufficient')divergences.push({priority:'P0',domain:'servicos',entity_id:s.id??null,reason:r.reason})}for(const a of input.agenda??[]){const life=agendaLifecycle(a);if(life.certainty==='insufficient')divergences.push({priority:'P0',domain:'agenda',entity_id:a.id??null,reason:life.reason});if(life.value==='planejado'){const certainty=agendaCertainty(a);if(certainty.certainty==='insufficient')divergences.push({priority:'P1',domain:'agenda',entity_id:a.id??null,reason:certainty.reason})}}for(const f of input.finance??[]){const r=isReceivedRevenue(f);if(r.certainty==='insufficient')divergences.push({priority:'P0',domain:'financeiro',entity_id:f.id??null,reason:r.reason})}return{ok:!divergences.some(d=>d.priority==='P0'),divergences}}
module.exports={serviceStage,agendaLifecycle,agendaCertainty,isReceivedRevenue,marketingAttribution,requiredHumanDecision,runChecks};
