
'use strict';
const KNOWN_AGENDA=new Set(['confirmado','provisorio','sugestao']);
const KNOWN_SERVICE=new Set(['orcamento','fechado','material','producao','entrega','encerrado']);
const ATTR_KEYS=['tracking_ref','gclid','gbraid','wbraid','utm_source','utm_medium','utm_campaign','campaign_id','ad_group_id','ad_id'];
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function result(value,certainty='known',reason=null){return{value,certainty,reason}}
function agendaState(item){const explicit=norm(item?.state);if(KNOWN_AGENDA.has(explicit))return result(explicit);if(!explicit)return result('estado_indeterminado','insufficient','agenda_sem_estado_explicito');return result('estado_indeterminado','insufficient','agenda_estado_desconhecido')}
function serviceStage(item){const explicit=norm(item?.stage);if(KNOWN_SERVICE.has(explicit))return result(explicit);if(!explicit)return result('etapa_indeterminada','insufficient','servico_sem_etapa_normalizada');return result('etapa_indeterminada','insufficient','servico_etapa_desconhecida')}
function isReceivedRevenue(entry){const direction=norm(entry?.direction),status=norm(entry?.status),scope=norm(entry?.scope),amount=Number(entry?.amount);if(direction!=='entrada')return result(false);if(scope&&scope!=='empresa')return result(false);if(!Number.isFinite(amount)||amount<=0)return result(false,'insufficient','valor_financeiro_invalido');if(status==='recebido')return result(true);if(!status)return result(false,'insufficient','entrada_sem_status_de_recebimento');return result(false)}
function marketingAttribution(record){const evidence=ATTR_KEYS.filter(k=>String(record?.[k]??'').trim());if(!evidence.length)return result(null,'insufficient','sem_evidencia_de_atribuicao');return result({evidence})}
function requiredHumanDecision(item){if(item?.ambiguity===true)return result(true,'known','ambiguidade_explicita');if(item?.external_write===true&&item?.approved!==true)return result(true,'known','escrita_externa_sem_aprovacao');if(item?.missing_required_fact===true)return result(true,'known','fato_obrigatorio_ausente');return result(false)}
function duplicateIds(items){const seen=new Set(),dup=new Set();for(const item of items??[]){const id=String(item?.id??'').trim();if(!id)continue;if(seen.has(id))dup.add(id);else seen.add(id)}return[...dup]}
function compare(domain,entityId,calculated,reference){if(calculated?.certainty==='insufficient')return{domain,entity_id:entityId,calculated,reference,result:'insuficiente',reason:calculated.reason};const a=JSON.stringify(calculated?.value),b=JSON.stringify(reference);return{domain,entity_id:entityId,calculated,reference,result:a===b?'igual':'divergente',reason:a===b?null:'valor_diferente'}}
function runChecks(input={}){const divergences=[];for(const a of input.agenda??[]){const r=agendaState(a);if(r.certainty==='insufficient')divergences.push({priority:'P0',domain:'agenda',entity_id:a.id??null,reason:r.reason})}for(const s of input.services??[]){const r=serviceStage(s);if(r.certainty==='insufficient')divergences.push({priority:'P0',domain:'servicos',entity_id:s.id??null,reason:r.reason})}for(const f of input.finance??[]){const r=isReceivedRevenue(f);if(r.certainty==='insufficient')divergences.push({priority:'P0',domain:'financeiro',entity_id:f.id??null,reason:r.reason})}for(const m of input.marketing??[]){const r=marketingAttribution(m);if(r.certainty==='insufficient')divergences.push({priority:'P0',domain:'crescimento',entity_id:m.id??null,reason:r.reason})}for(const d of duplicateIds(input.clients))divergences.push({priority:'P0',domain:'clientes',entity_id:d,reason:'id_duplicado'});return{ok:divergences.length===0,divergences}}
const api={agendaState,serviceStage,isReceivedRevenue,marketingAttribution,requiredHumanDecision,duplicateIds,compare,runChecks};if(typeof module!=='undefined')module.exports=api;if(typeof window!=='undefined')window.BahiaShadowCore=api;
