import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const SUPABASE_URL="https://recmmjglkbcedqkajnzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_LMjrXNWZvpX9NRLejNGepw_prFGYWVq";
const SHADOW_URL=`${SUPABASE_URL}/functions/v1/v4-shadow-read`;
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const shortId=id=>esc(String(id??"").slice(0,8));const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));
const metric=(value,label,detail)=>`<article class="metric card"><b>${esc(value)}</b><span>${esc(label)}</span><small>${esc(detail)}</small></article>`;const row=(title,detail,badge)=>`<div class="row"><div><strong>${esc(title)}</strong><small>${esc(detail)}</small></div><span class="badge info">${esc(badge)}</span></div>`;
function showLogin(message=""){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden");$("loginError").textContent=message}function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden")}
async function shadowRead(){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return showLogin("Sessão ausente. Entre novamente.");$("syncBadge").textContent="carregando";const res=await fetch(`${SHADOW_URL}?limit=100`,{method:"GET",headers:{Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY},cache:"no-store"});if(res.status===401||res.status===403){await supabase.auth.signOut();return showLogin("Sessão sem autorização para o staging.")}if(!res.ok)throw new Error(`shadow_read_${res.status}`);const body=await res.json();const clients=Array.isArray(body.clients)?body.clients:[];const services=Array.isArray(body.services)?body.services:[];const agenda=Array.isArray(body.agenda)?body.agenda:[];const finance=Array.isArray(body.finance)?body.finance:[];$("metrics").innerHTML=metric(clients.length,"clientes","campos técnicos, sem PII")+metric(services.length,"serviços","estados do staging")+metric(agenda.length,"agenda","somente leitura")+metric(finance.length,"financeiro","nenhuma baixa");$("services").innerHTML=services.map(s=>row(`#${shortId(s.id)} · ${s.status}`,`prioridade ${s.prioridade??"—"} · prazo ${s.prazo??"—"}`,s.tracking_ref?"atribuído":"sem tracking")).join("")||row("Nenhum serviço","staging vazio","ok");$("agenda").innerHTML=agenda.map(a=>row(`${a.data} · ${a.hora??"sem hora"}`,`${a.cidade??"sem cidade"} · ${a.tipo??"—"}`,a.status??"—")).join("")||row("Agenda vazia","sem compromissos","ok");$("finance").innerHTML=finance.map(f=>row(`${f.tipo} · ${money(f.valor)}`,`${f.escopo} · ${f.categoria??"sem categoria"} · ${f.data}`,f.status??"—")).join("")||row("Financeiro vazio","sem fatos","ok");$("clients").innerHTML=clients.map(c=>row(`#${shortId(c.id)}`,`${c.cidade??"sem cidade"} · criado ${String(c.criado_em??"").slice(0,10)}`,"sem PII")).join("")||row("Nenhum cliente","staging vazio","ok");$("captured").textContent=`Leitura concluída em ${new Date(body.captured_at).toLocaleString("pt-BR")}. Dados vindos apenas do Supabase V4 Staging.`;$("syncBadge").textContent="sincronizado";showApp()}
$("loginForm").addEventListener("submit",async ev=>{ev.preventDefault();$("loginError").textContent="Autenticando…";const{error}=await supabase.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)return $("loginError").textContent="Login de staging inválido.";$("loginError").textContent="";try{await shadowRead()}catch{showLogin("Falha ao ler o staging.")}});$("refreshBtn").addEventListener("click",()=>shadowRead().catch(()=>alert("Falha ao atualizar o staging.")));$("logoutBtn").addEventListener("click",async()=>{await supabase.auth.signOut();showLogin()});const{data:{session}}=await supabase.auth.getSession();if(session)shadowRead().catch(()=>showLogin("Falha ao restaurar a sessão do staging."));else showLogin();